### ISSUE TITLE
connection refuse should handle properly

### ISSUE THREAD

**Issue by ugurengin** [ugurengin/redis-slave-check#2]
Traceback (most recent call last)​:
File "/usr/lib64/nagios/plugins/check_​redis_​slave.​py", line 46, in <module>
    valid_​redis​()
  File "/usr/lib64/nagios/plugins/check_​redis_​slave.​py", line 38, in valid_​redis
    i = r.​info​()
  File "/usr/lib/python2.​7/site-​packages/redis/client.​py", line 657, in info
    return self.​execute_​command​('INFO')
  File "/usr/lib/python2.​7/site-​packages/redis/client.​py", line 570, in execute_​command
    connection.​send_​command​(_args)
  File "/usr/lib/python2.​7/site-​packages/redis/connection.​py", line 556, in send_​command
    self.​send_​packed_​command​(self.​pack_​command​(_args)​)
  File "/usr/lib/python2.​7/site-​packages/redis/connection.​py", line 532, in send_​packed_​command
    self.​connect​()
  File "/usr/lib/python2.​7/site-​packages/redis/connection.​py", line 436, in connect
    raise ConnectionError​(self.​_error_​message​(e)​)
redis.​exceptions.​ConnectionError: Error 111 connecting to <redis-host>:​6379. Connection refused.
- It should be return call 3 when default connection is refused during single check at running.

**Comment by ugurengin** [comment]
This cause is fixed:
https://github.com/ugurengin/redis-slave-check/commit/a982a43a5b95e2ec4b2dfb86d0c7664fa862c214
